### ISSUE TITLE
Malicious hook that reverts when removing liquidity

### ISSUE THREAD

**Issue by egozoq** [Uniswap/v4-core#561]
### Component

Hooks

### Describe the suggested feature and problem it solves.

Given that hooks are run `before` and `after` inside a function, it becomes possible to create a hook that allows depositing of liqudity into a pool, but when removing, the hook will revert.

This would essentially lock any liquidity that is deposited, stuck forever inside the pool.

---

I think another potential malicious way to implement this would be to use up all the gas inside a hook, so that when the hook returns, it's out of gas and the whole transaction would revert. In this scenario, even if the code in `PoolManager.sol` is amended to ignore potential reverts, you'd still be susceptible to out-of-gas attacks.

Would be great to hear from others what you'd think about this potential attack vectors, and whether this is something that should be addressed or not.

For example, one could argue that it's up to the user to vet each pool for malicious hooks, but that changes the UX of Uniswap drastically. Today, you can safely add liq without worrying about being rugged. That wouldn't be the case for V4, I think? Anyways, would be cool to hear from others on this.

**Comment by fuelmessenger** [comment]
:sparkles: Thanks to the community, there's an estimated bounty value of **$555.93 USD** for a successful merge request of this issue via contributions such as **49.725 UNI** tokens. Happy coding :grinning:
Details and T&Cs at [joinfuel.io](https://joinfuel.io)

**Comment by zemse** [comment]
It could also be possible to design a hook that allows people to buy a token but then able to sell it. The revert in this case could be on any of before or after swap hook.

Pool manager could do tricks to make it harder to design such a hook, like ignoring reverts, prevent out-of-gas by retaining enough gas in pool manager instead of passing all gas. But ignoring reverts would break bunch of [hooks](https://github.com/ora-io/awesome-uniswap-hooks?tab=readme-ov-file#from-community).

There were incidents with during the last season where people were buying malicious tokens on v2 and getting rugged. But the uniswap frontend had whitelisted popular tokens and buying a shady token required extra steps. I feel for most users, a whitelist of hooks could be useful, while a user who knows what they are doing could take extra steps to interact with a shady hook and there be a process to whitelist hooks with a new codehash.

**Comment by snreynolds** [comment]
Thanks for the comment! This is a known behavior of hooks, and this is not something we aim to solve in PoolManager. Like tokens, hooks can be created to be malicious in this way and it is up to users and interfaces to do proper due diligence if integrating a pool with a hook.

I will note that it is not possible for a hook's permissions to be changed after creation because these permissions are enshrined in the pool key (through the hook address). This is a nice feature as an integrator will always know the severity of permissions the hook has. Any hook with a before/after removeLiquidity flag should be used cautiously.
